export interface ExpressionInfo {
    type: string;
    description: string;
    example?: string;
}

export interface StepOptionInfo {
    description: string;
    values?: string[];
    snippet?: string;
}

// All DSL expressions with documentation
export const EXPRESSIONS: Record<string, ExpressionInfo> = {
    // Resources
    'energy': { type: 'resource', description: 'Current energy value', example: 'if=energy>=50' },
    'energy.max': { type: 'resource', description: 'Maximum energy', example: 'if=energy=energy.max' },
    'energy.deficit': { type: 'resource', description: 'Energy deficit (max - current)', example: 'if=energy.deficit<20' },
    'energy.pct': { type: 'resource', description: 'Energy percentage (0-100)', example: 'if=energy.pct>50' },
    'energy.regen': { type: 'resource', description: 'Energy regeneration rate', example: 'if=energy.regen>15' },
    'energy.time_to_max': { type: 'resource', description: 'Seconds until energy is full', example: 'if=energy.time_to_max<3' },

    'rage': { type: 'resource', description: 'Current rage value', example: 'if=rage>=30' },
    'rage.max': { type: 'resource', description: 'Maximum rage', example: 'if=rage=rage.max' },
    'rage.deficit': { type: 'resource', description: 'Rage deficit', example: 'if=rage.deficit<20' },

    'runic_power': { type: 'resource', description: 'Current runic power', example: 'if=runic_power>=80' },
    'runic_power.max': { type: 'resource', description: 'Maximum runic power' },
    'runic_power.deficit': { type: 'resource', description: 'Runic power deficit' },

    'rune': { type: 'resource', description: 'Available rune count', example: 'if=rune>=3' },

    'focus': { type: 'resource', description: 'Current focus value', example: 'if=focus>=50' },
    'focus.max': { type: 'resource', description: 'Maximum focus' },
    'focus.deficit': { type: 'resource', description: 'Focus deficit' },
    'focus.pct': { type: 'resource', description: 'Focus percentage' },
    'focus.regen': { type: 'resource', description: 'Focus regeneration rate' },
    'focus.time_to_max': { type: 'resource', description: 'Seconds until focus is full' },

    'mana': { type: 'resource', description: 'Current mana value', example: 'if=mana>=1000' },
    'mana.max': { type: 'resource', description: 'Maximum mana' },
    'mana.deficit': { type: 'resource', description: 'Mana deficit' },
    'mana.pct': { type: 'resource', description: 'Mana percentage', example: 'if=mana.pct>30' },
    'mana.regen': { type: 'resource', description: 'Mana regeneration rate' },
    'mana.time_to_max': { type: 'resource', description: 'Seconds until mana is full' },

    'combo_points': { type: 'resource', description: 'Current combo points', example: 'if=combo_points>=5' },
    'combo_points.max': { type: 'resource', description: 'Maximum combo points' },
    'combo_points.deficit': { type: 'resource', description: 'Combo points deficit' },

    'soul_shards': { type: 'resource', description: 'Current soul shards (Warlock)' },
    'holy_power': { type: 'resource', description: 'Current holy power (Paladin)' },
    'chi': { type: 'resource', description: 'Current chi (Monk)' },
    'insanity': { type: 'resource', description: 'Current insanity (Shadow Priest)' },
    'stagger': { type: 'resource', description: 'Current stagger amount (Brewmaster)' },
    'stagger.pct': { type: 'resource', description: 'Stagger as % of max health', example: 'if=stagger.pct>60' },
    'arcane_charges': { type: 'resource', description: 'Current arcane charges (Arcane Mage)' },
    'fury': { type: 'resource', description: 'Current fury (Demon Hunter)' },
    'pain': { type: 'resource', description: 'Current pain (Vengeance DH)' },
    'maelstrom': { type: 'resource', description: 'Current maelstrom (Enhancement Shaman)' },
    'astral_power': { type: 'resource', description: 'Current astral power (Balance Druid)' },
    'lunar_power': { type: 'resource', description: 'Alias for astral_power (Balance Druid)' },
    'essence': { type: 'resource', description: 'Current essence (Evoker)' },
    'soul_shard': { type: 'resource', description: 'Alias for soul_shards (Warlock)' },

    // Health
    'health.current': { type: 'health', description: 'Player current health value', example: 'if=health.current<200000' },
    'health.pct': { type: 'health', description: 'Player health percentage (0-100)', example: 'if=health.pct<=30' },
    'health.deficit': { type: 'health', description: 'Player missing health amount', example: 'if=health.deficit>50000' },

    'player.health.current': { type: 'health', description: 'Player current health value' },
    'player.health.pct': { type: 'health', description: 'Player health percentage' },
    'player.health.deficit': { type: 'health', description: 'Player missing health' },
    'player.health.max': { type: 'health', description: 'Player maximum health' },

    'target.health.current': { type: 'health', description: 'Target current health value' },
    'target.health.pct': { type: 'health', description: 'Target health percentage', example: 'if=target.health.pct<=20' },
    'target.health.deficit': { type: 'health', description: 'Target missing health amount' },
    'target.time_to_die': { type: 'health', description: 'Estimated seconds until target dies', example: 'if=target.time_to_die>15' },
    'time_to_die': { type: 'health', description: 'Alias for target.time_to_die' },
    'fight_remains': { type: 'health', description: 'Estimated time remaining in fight' },
    'range': { type: 'target', description: 'Alias for target.range (distance in yards)', example: 'if=range<8' },

    'focus.health.current': { type: 'health', description: 'Focus target current health value' },
    'focus.health.pct': { type: 'health', description: 'Focus target health percentage' },
    'focus.health.deficit': { type: 'health', description: 'Focus target missing health amount' },

    'mouseover.health.current': { type: 'health', description: 'Mouseover current health value' },
    'mouseover.health.pct': { type: 'health', description: 'Mouseover health percentage' },
    'mouseover.health.deficit': { type: 'health', description: 'Mouseover missing health amount' },

    'pet.health.current': { type: 'health', description: 'Pet current health value' },
    'pet.health.pct': { type: 'health', description: 'Pet health percentage', example: 'if=pet.health.pct<40' },
    'pet.health.deficit': { type: 'health', description: 'Pet missing health amount' },

    // Buffs (templates - SPELL is placeholder)
    'buff.SPELL.up': { type: 'buff', description: 'Player-applied buff is active (1 if true, 0 if false). Use .any for any source.', example: 'if=buff.bloodlust.up' },
    'buff.SPELL.down': { type: 'buff', description: 'Player-applied buff is NOT active. Use .any for any source.', example: 'if=buff.shield.down' },
    'buff.SPELL.remains': { type: 'buff', description: 'Time remaining in seconds (player-applied). Use .any for any source.', example: 'if=buff.haste_buff.remains<5' },
    'buff.SPELL.elapsed': { type: 'buff', description: 'Time since application in seconds (player-applied). Use .any for any source.', example: 'if=buff.my_buff.elapsed>3' },
    'buff.SPELL.stack': { type: 'buff', description: 'Current stack count (player-applied). Use .any for any source.', example: 'if=buff.power_stacks.stack>=3' },
    'buff.SPELL.duration': { type: 'buff', description: 'Base duration of the buff (player-applied). Use .any for any source.' },
    'buff.SPELL.refreshable': { type: 'buff', description: 'Buff can be refreshed (pandemic window, player-applied). Use .any for any source.' },
    'buff.SPELL.react': { type: 'buff', description: 'Buff is active (same as .up, for procs, player-applied). Use .any for any source.' },
    'buff.SPELL.up.any': { type: 'buff', description: 'Buff is active from any source', example: 'if=buff.bloodlust.up.any' },
    'buff.SPELL.down.any': { type: 'buff', description: 'Buff is NOT active from any source' },
    'buff.SPELL.remains.any': { type: 'buff', description: 'Time remaining in seconds (any source)' },
    'buff.SPELL.elapsed.any': { type: 'buff', description: 'Time since application in seconds (any source)' },
    'buff.SPELL.stack.any': { type: 'buff', description: 'Current stack count (any source)' },
    'buff.SPELL.duration.any': { type: 'buff', description: 'Base duration of the buff (any source)' },
    'buff.SPELL.refreshable.any': { type: 'buff', description: 'Buff can be refreshed (pandemic window, any source)' },
    'buff.SPELL.react.any': { type: 'buff', description: 'Buff is active (same as .up, any source)' },
    'buff.SPELL.stealable': { type: 'buff', description: 'Buff can be stolen (player-applied by default). Use .any for any source.' },
    'buff.SPELL.magic': { type: 'buff', description: 'Buff is Magic dispel type (player-applied by default). Use .any for any source.' },
    'buff.SPELL.curse': { type: 'buff', description: 'Buff is Curse dispel type (player-applied by default). Use .any for any source.' },
    'buff.SPELL.disease': { type: 'buff', description: 'Buff is Disease dispel type (player-applied by default). Use .any for any source.' },
    'buff.SPELL.poison': { type: 'buff', description: 'Buff is Poison dispel type (player-applied by default). Use .any for any source.' },
    'buff.SPELL.icon': { type: 'buff', description: 'Buff icon ID (player-applied by default). Use .any for any source.' },
    'buff.SPELL.mine': { type: 'buff', description: 'Buff was applied by player' },
    'buff.SPELL.stealable.any': { type: 'buff', description: 'Buff can be stolen (any source)' },
    'buff.SPELL.magic.any': { type: 'buff', description: 'Buff is Magic dispel type (any source)' },
    'buff.SPELL.curse.any': { type: 'buff', description: 'Buff is Curse dispel type (any source)' },
    'buff.SPELL.disease.any': { type: 'buff', description: 'Buff is Disease dispel type (any source)' },
    'buff.SPELL.poison.any': { type: 'buff', description: 'Buff is Poison dispel type (any source)' },
    'buff.SPELL.icon.any': { type: 'buff', description: 'Buff icon ID (any source)' },

    // Debuffs
    'debuff.SPELL.up': { type: 'debuff', description: 'Player-applied debuff is active on target. Use .any for any source.', example: 'if=debuff.vulnerability.up' },
    'debuff.SPELL.down': { type: 'debuff', description: 'Player-applied debuff is NOT on target. Use .any for any source.', example: 'if=debuff.curse.down' },
    'debuff.SPELL.remains': { type: 'debuff', description: 'Time remaining (player-applied). Use .any for any source.', example: 'if=debuff.poison.remains<3' },
    'debuff.SPELL.elapsed': { type: 'debuff', description: 'Time since application in seconds (player-applied). Use .any for any source.', example: 'if=debuff.dot.elapsed>3' },
    'debuff.SPELL.stack': { type: 'debuff', description: 'Stack count (player-applied). Use .any for any source.', example: 'if=debuff.wound.stack<5' },
    'debuff.SPELL.duration': { type: 'debuff', description: 'Base duration of the debuff (player-applied). Use .any for any source.' },
    'debuff.SPELL.refreshable': { type: 'debuff', description: 'Debuff can be refreshed (player-applied). Use .any for any source.' },
    'debuff.SPELL.ticking': { type: 'debuff', description: 'Debuff is active (alias of .up, player-applied). Use .any for any source.' },
    'debuff.SPELL.up.any': { type: 'debuff', description: 'Debuff is active on target from any source' },
    'debuff.SPELL.down.any': { type: 'debuff', description: 'Debuff is NOT on target from any source' },
    'debuff.SPELL.remains.any': { type: 'debuff', description: 'Time remaining (any source)' },
    'debuff.SPELL.elapsed.any': { type: 'debuff', description: 'Time since application in seconds (any source)' },
    'debuff.SPELL.stack.any': { type: 'debuff', description: 'Stack count (any source)' },
    'debuff.SPELL.duration.any': { type: 'debuff', description: 'Base duration of the debuff (any source)' },
    'debuff.SPELL.refreshable.any': { type: 'debuff', description: 'Debuff can be refreshed (any source)' },
    'debuff.SPELL.ticking.any': { type: 'debuff', description: 'Debuff is active (alias of .up, any source)' },
    'debuff.SPELL.stealable': { type: 'debuff', description: 'Debuff can be stolen (player-applied by default). Use .any for any source.' },
    'debuff.SPELL.magic': { type: 'debuff', description: 'Debuff is Magic dispel type (player-applied by default). Use .any for any source.' },
    'debuff.SPELL.curse': { type: 'debuff', description: 'Debuff is Curse dispel type (player-applied by default). Use .any for any source.' },
    'debuff.SPELL.disease': { type: 'debuff', description: 'Debuff is Disease dispel type (player-applied by default). Use .any for any source.' },
    'debuff.SPELL.poison': { type: 'debuff', description: 'Debuff is Poison dispel type (player-applied by default). Use .any for any source.' },
    'debuff.SPELL.icon': { type: 'debuff', description: 'Debuff icon ID (player-applied by default). Use .any for any source.' },
    'debuff.SPELL.mine': { type: 'debuff', description: 'Debuff was applied by player' },
    'debuff.SPELL.stealable.any': { type: 'debuff', description: 'Debuff can be stolen (any source)' },
    'debuff.SPELL.magic.any': { type: 'debuff', description: 'Debuff is Magic dispel type (any source)' },
    'debuff.SPELL.curse.any': { type: 'debuff', description: 'Debuff is Curse dispel type (any source)' },
    'debuff.SPELL.disease.any': { type: 'debuff', description: 'Debuff is Disease dispel type (any source)' },
    'debuff.SPELL.poison.any': { type: 'debuff', description: 'Debuff is Poison dispel type (any source)' },
    'debuff.SPELL.icon.any': { type: 'debuff', description: 'Debuff icon ID (any source)' },

    // DoTs
    'dot.SPELL.ticking': { type: 'dot', description: 'DoT is active (player-applied by default). Use .any for any source.', example: 'if=dot.corruption.ticking' },
    'dot.SPELL.remains': { type: 'dot', description: 'DoT time remaining (player-applied by default). Use .any for any source.', example: 'if=dot.corruption.remains<3' },
    'dot.SPELL.elapsed': { type: 'dot', description: 'Time since DoT application in seconds (player-applied by default). Use .any for any source.' },
    'dot.SPELL.stack': { type: 'dot', description: 'DoT stack count (player-applied by default). Use .any for any source.' },
    'dot.SPELL.duration': { type: 'dot', description: 'DoT base duration (player-applied by default). Use .any for any source.' },
    'dot.SPELL.refreshable': { type: 'dot', description: 'DoT can be refreshed (pandemic, player-applied by default). Use .any for any source.' },
    'dot.SPELL.ticking.any': { type: 'dot', description: 'DoT is active from any source' },
    'dot.SPELL.remains.any': { type: 'dot', description: 'DoT time remaining from any source' },
    'dot.SPELL.elapsed.any': { type: 'dot', description: 'Time since DoT application in seconds (any source)' },
    'dot.SPELL.stack.any': { type: 'dot', description: 'DoT stack count from any source' },
    'dot.SPELL.duration.any': { type: 'dot', description: 'DoT base duration from any source' },
    'dot.SPELL.refreshable.any': { type: 'dot', description: 'DoT can be refreshed (pandemic, any source)' },
    'active_dot.SPELL': { type: 'dot', description: 'Count of enemies with your DoT (player-applied only). Use .any for all sources.', example: 'if=active_dot.corruption>=3' },
    'active_dot.SPELL.any': { type: 'dot', description: 'Count of enemies with a DoT from any source', example: 'if=active_dot.corruption.any>=3' },

    // Cooldowns
    'cooldown.SPELL.ready': { type: 'cooldown', description: 'Spell is ready (off cooldown)', example: 'if=cooldown.big_damage.ready' },
    'cooldown.SPELL.up': { type: 'cooldown', description: 'Same as .ready' },
    'cooldown.SPELL.down': { type: 'cooldown', description: 'Spell is on cooldown' },
    'cooldown.SPELL.remains': { type: 'cooldown', description: 'Time until ready', example: 'if=cooldown.burst.remains<5' },
    'cooldown.SPELL.charges': { type: 'cooldown', description: 'Current charge count', example: 'if=cooldown.blink.charges>=1' },
    'cooldown.SPELL.max_charges': { type: 'cooldown', description: 'Maximum charges' },
    'cooldown.SPELL.full_recharge_time': { type: 'cooldown', description: 'Time until all charges restored' },
    'cooldown.SPELL.charges_fractional': { type: 'cooldown', description: 'Charges including partial progress' },

    // Usable/Range
    'usable.SPELL': { type: 'spell', description: 'Spell is usable (resources + off CD)', example: 'if=usable.expensive_ability' },
    'range.SPELL.target': { type: 'range', description: 'Spell is in range for target', example: 'if=range.snipe.target' },
    'range.SPELL.focus': { type: 'range', description: 'Spell is in range for focus' },
    'range.SPELL.mouseover': { type: 'range', description: 'Spell is in range for mouseover' },

    // Talents
    'talent.TALENT': { type: 'talent', description: 'Talent is selected (1 if true)', example: 'if=talent.improved_spell' },
    'talent.TALENT.enabled': { type: 'talent', description: 'Talent is selected' },
    'talent.TALENT.rank': { type: 'talent', description: 'Talent rank (0 if not selected)', example: 'if=talent.power_talent.rank>=2' },
    'player.talent(SPELL)': { type: 'talent', description: 'Check if talent is selected (function syntax)', example: 'if=player.talent(combustion)' },

    // Action properties
    'action.SPELL.charges': { type: 'action', description: 'Action charges' },
    'action.SPELL.cast_time': { type: 'action', description: 'Cast time in seconds' },
    'action.SPELL.execute_time': { type: 'action', description: 'Max of cast_time and GCD' },

    // GCD
    'gcd': { type: 'gcd', description: 'Current GCD duration', example: 'if=gcd<1.2' },
    'gcd.max': { type: 'gcd', description: 'Maximum GCD (usually 1.5s)' },
    'gcd.remains': { type: 'gcd', description: 'Time until GCD expires', example: 'if=gcd.remains<0.2' },
    'player.gcd': { type: 'gcd', description: 'Current GCD duration' },
    'player.gcd.remains': { type: 'gcd', description: 'Time until GCD expires' },

    // Previous cast
    'prev_gcd.1.SPELL': { type: 'prev', description: 'Last GCD was this spell', example: 'if=prev_gcd.1.setup_spell' },
    'prev_gcd.2.SPELL': { type: 'prev', description: 'Two GCDs ago was this spell' },
    'prev_gcd.3.SPELL': { type: 'prev', description: 'Three GCDs ago was this spell' },
    'player.prev_gcd_1(SPELL)': { type: 'prev', description: 'Last GCD was this spell (function syntax)', example: 'if=player.prev_gcd_1(fireball)' },
    'player.prev_gcd_2(SPELL)': { type: 'prev', description: 'Two GCDs ago was this spell (function syntax)' },
    'player.prev_gcd_3(SPELL)': { type: 'prev', description: 'Three GCDs ago was this spell (function syntax)' },

    // Player buff/debuff function syntax
    'player.buff.remains(SPELL)': { type: 'buff', description: 'Player buff remaining duration (function syntax)', example: 'if=player.buff.remains(bloodlust)>10' },
    'player.buff.stacks(SPELL)': { type: 'buff', description: 'Player buff stack count (function syntax)' },
    'player.buff.up(SPELL)': { type: 'buff', description: 'Player has buff (function syntax)', example: 'if=player.buff.up(bloodlust)' },
    'player.debuff.remains(SPELL)': { type: 'debuff', description: 'Player debuff remaining duration (function syntax)' },
    'player.debuff.stacks(SPELL)': { type: 'debuff', description: 'Player debuff stack count (function syntax)' },
    'player.debuff.up(SPELL)': { type: 'debuff', description: 'Player has debuff (function syntax)' },

    // Target debuff function syntax
    'target.debuff.remains(SPELL)': { type: 'debuff', description: 'Target debuff remaining duration (function syntax)', example: 'if=target.debuff.remains(corruption)>3' },
    'target.debuff.stacks(SPELL)': { type: 'debuff', description: 'Target debuff stack count (function syntax)' },
    'target.debuff.up(SPELL)': { type: 'debuff', description: 'Target has debuff (function syntax)', example: 'if=target.debuff.up(corruption)' },
    'target.buff.remains(SPELL)': { type: 'buff', description: 'Target buff remaining duration (function syntax)' },
    'target.buff.stacks(SPELL)': { type: 'buff', description: 'Target buff stack count (function syntax)' },
    'target.buff.up(SPELL)': { type: 'buff', description: 'Target has buff (function syntax)' },

    // Player state
    'player.dead': { type: 'state', description: 'Player is dead' },
    'player.alive': { type: 'state', description: 'Player is alive' },
    'player.moving': { type: 'state', description: 'Player is moving', example: 'if=!player.moving' },
    'player.moving.time': { type: 'state', description: 'Seconds player has been moving' },
    'player.standing': { type: 'state', description: 'Player is standing still' },
    'player.standing.time': { type: 'state', description: 'Seconds standing still' },
    'player.mounted': { type: 'state', description: 'Player is mounted' },
    'player.in_vehicle': { type: 'state', description: 'Player is in a vehicle' },
    'player.casting': { type: 'state', description: 'Player is casting', example: 'if=!player.casting' },
    'player.channeling': { type: 'state', description: 'Player is channeling' },
    'player.casting.spell': { type: 'state', description: 'Currently casting spell ID' },
    'player.casting.remains': { type: 'state', description: 'Time remaining on cast' },
    'player.casting.elapsed': { type: 'state', description: 'Time spent casting' },
    'player.combat': { type: 'state', description: 'Player is in combat' },
    'player.combat.time': { type: 'state', description: 'Time in combat (seconds)', example: 'if=player.combat.time<5' },
    'player.empower_stage': { type: 'state', description: 'Evoker empower stage (1-4)', example: 'if=player.empower_stage>=2' },
    'player.burst.active': { type: 'state', description: 'Any burst buff is active', example: 'if=player.burst.active' },
    'player.burst.count': { type: 'state', description: 'Number of active burst buffs' },

    // Short aliases (without player. prefix)
    'dead': { type: 'state', description: 'Alias for player.dead' },
    'alive': { type: 'state', description: 'Alias for player.alive' },
    'moving': { type: 'state', description: 'Alias for player.moving', example: 'if=!moving' },
    'moving.time': { type: 'state', description: 'Alias for player.moving.time' },
    'standing': { type: 'state', description: 'Alias for player.standing' },
    'standing.time': { type: 'state', description: 'Alias for player.standing.time' },
    'mounted': { type: 'state', description: 'Alias for player.mounted' },
    'casting': { type: 'state', description: 'Alias for player.casting', example: 'if=!casting' },
    'channeling': { type: 'state', description: 'Alias for player.channeling' },
    'casting.remains': { type: 'state', description: 'Alias for player.casting.remains' },
    'casting.elapsed': { type: 'state', description: 'Alias for player.casting.elapsed' },
    'casting.spell': { type: 'state', description: 'Alias for player.casting.spell' },
    'combat': { type: 'state', description: 'Alias for player.combat' },
    'combat.time': { type: 'state', description: 'Alias for player.combat.time' },
    'empower_stage': { type: 'state', description: 'Alias for player.empower_stage (Evoker)' },
    'boss_fight': { type: 'zone', description: 'Alias for player.boss_fight' },

    // Player CC/LoC
    'player.stunned': { type: 'cc', description: 'Player is stunned', example: 'if=player.stunned' },
    'player.stunned.remains': { type: 'cc', description: 'Stun duration remaining' },
    'player.rooted': { type: 'cc', description: 'Player is rooted' },
    'player.rooted.remains': { type: 'cc', description: 'Root duration remaining' },
    'player.feared': { type: 'cc', description: 'Player is feared' },
    'player.silenced': { type: 'cc', description: 'Player is silenced' },
    'player.incapacitated': { type: 'cc', description: 'Player is incapacitated' },
    'player.charmed': { type: 'cc', description: 'Player is mind controlled' },
    'player.disarmed': { type: 'cc', description: 'Player is disarmed' },
    'player.cc': { type: 'cc', description: 'Player cannot act (stunned/feared/etc)', example: 'if=player.cc' },
    'player.feared.remains': { type: 'cc', description: 'Fear duration remaining' },
    'player.silenced.remains': { type: 'cc', description: 'Silence duration remaining' },
    'player.incapacitated.remains': { type: 'cc', description: 'Incapacitate duration remaining' },
    'player.charmed.remains': { type: 'cc', description: 'Charm duration remaining' },
    'player.disarmed.remains': { type: 'cc', description: 'Disarm duration remaining' },
    'player.stunned.elapsed': { type: 'cc', description: 'Time since stunned' },
    'player.rooted.elapsed': { type: 'cc', description: 'Time since rooted' },
    'player.feared.elapsed': { type: 'cc', description: 'Time since feared' },
    'player.silenced.elapsed': { type: 'cc', description: 'Time since silenced' },
    'player.incapacitated.elapsed': { type: 'cc', description: 'Time since incapacitated' },
    'player.charmed.elapsed': { type: 'cc', description: 'Time since charmed' },
    'player.disarmed.elapsed': { type: 'cc', description: 'Time since disarmed' },

    // Short aliases for CC (without player. prefix)
    'stunned': { type: 'cc', description: 'Alias for player.stunned' },
    'stunned.remains': { type: 'cc', description: 'Alias for player.stunned.remains' },
    'stunned.elapsed': { type: 'cc', description: 'Alias for player.stunned.elapsed' },
    'rooted': { type: 'cc', description: 'Alias for player.rooted' },
    'rooted.remains': { type: 'cc', description: 'Alias for player.rooted.remains' },
    'rooted.elapsed': { type: 'cc', description: 'Alias for player.rooted.elapsed' },
    'silenced': { type: 'cc', description: 'Alias for player.silenced' },
    'silenced.remains': { type: 'cc', description: 'Alias for player.silenced.remains' },
    'silenced.elapsed': { type: 'cc', description: 'Alias for player.silenced.elapsed' },

    // Player role
    'player.tank': { type: 'role', description: 'Player is a tank', example: 'if=player.tank' },
    'player.healer': { type: 'role', description: 'Player is a healer' },
    'player.dps': { type: 'role', description: 'Player is DPS' },
    'player.melee': { type: 'role', description: 'Player uses melee attacks' },
    'player.ranged': { type: 'role', description: 'Player uses ranged attacks' },
    'player.evoker': { type: 'role', description: 'Player is an Evoker' },

    // Player stats
    'player.haste_pct': { type: 'stat', description: 'Haste percentage', example: 'if=player.haste_pct>=30' },
    'player.haste': { type: 'stat', description: 'Haste percentage (alias)' },
    'player.crit_pct': { type: 'stat', description: 'Critical strike percentage' },
    'player.crit': { type: 'stat', description: 'Critical strike percentage (alias)' },
    'player.versa_pct': { type: 'stat', description: 'Versatility percentage' },
    'player.versatility': { type: 'stat', description: 'Versatility percentage (alias)' },
    'player.mastery_pct': { type: 'stat', description: 'Mastery percentage' },
    'player.mastery': { type: 'stat', description: 'Mastery percentage (alias)' },

    // Short aliases for stats (without player. prefix)
    'haste_pct': { type: 'stat', description: 'Alias for player.haste_pct' },
    'haste': { type: 'stat', description: 'Alias for player.haste' },
    'crit_pct': { type: 'stat', description: 'Alias for player.crit_pct' },
    'crit': { type: 'stat', description: 'Alias for player.crit' },
    'versa_pct': { type: 'stat', description: 'Alias for player.versa_pct' },
    'versatility': { type: 'stat', description: 'Alias for player.versatility' },
    'mastery_pct': { type: 'stat', description: 'Alias for player.mastery_pct' },
    'mastery': { type: 'stat', description: 'Alias for player.mastery' },

    // Player instance/zone
    'player.indungeon': { type: 'zone', description: 'Player is in a dungeon' },
    'player.inraid': { type: 'zone', description: 'Player is in a raid' },
    'player.inpvecontent': { type: 'zone', description: 'In dungeon, raid, or delve' },
    'player.inmythicplus': { type: 'zone', description: 'In active M+ keystone', example: 'if=player.inmythicplus' },
    'player.inarena': { type: 'zone', description: 'In arena' },
    'player.inpvp': { type: 'zone', description: 'In battleground' },
    'player.ininstancedpvp': { type: 'zone', description: 'In arena or battleground' },
    'player.indelve': { type: 'zone', description: 'In a delve' },
    'player.inscenario': { type: 'zone', description: 'In a scenario' },
    'player.keystonelevel': { type: 'zone', description: 'Current M+ keystone level', example: 'if=player.keystonelevel>=15' },
    'player.boss_fight': { type: 'zone', description: 'Boss unit frames exist' },

    // Player debuff checks
    'player.has_magic_debuff': { type: 'debuff', description: 'Player has any magic debuff' },
    'player.has_curse': { type: 'debuff', description: 'Player has any curse debuff' },
    'player.has_disease': { type: 'debuff', description: 'Player has any disease debuff' },
    'player.has_poison': { type: 'debuff', description: 'Player has any poison debuff' },

    // Target
    'target.exists': { type: 'target', description: 'Target exists', example: 'if=target.exists' },
    'target.alive': { type: 'target', description: 'Target is alive' },
    'target.dead': { type: 'target', description: 'Target is dead' },
    'target.enemy': { type: 'target', description: 'Target is an enemy' },
    'target.friendly': { type: 'target', description: 'Target is friendly' },
    'target.boss': { type: 'target', description: 'Target is a boss', example: 'if=target.boss' },
    'target.range': { type: 'target', description: 'Distance to target in yards', example: 'if=target.range<8' },
    'target.moving': { type: 'target', description: 'Target is moving' },
    'target.casting': { type: 'target', description: 'Target is casting' },
    'target.channeling': { type: 'target', description: 'Target is channeling' },
    'target.casting.spell': { type: 'target', description: 'Target casting spell ID' },
    'target.casting.remains': { type: 'target', description: 'Target cast time remaining' },
    'target.casting.elapsed': { type: 'target', description: 'Target cast time elapsed' },
    'target.casting.interruptible': { type: 'target', description: 'Target cast can be interrupted', example: 'if=target.casting.interruptible' },
    'target.casting.important': { type: 'target', description: 'Target cast is in _interrupts.yaml' },
    'target.casting.targeting_me': { type: 'target', description: 'Target cast is targeting player' },
    'target.casting.SPELL_NAME': { type: 'target', description: 'Target is casting specific spell by name', example: 'if=target.casting.shadow_bolt' },
    'target.valid': { type: 'target', description: 'Comprehensive target check (exists, enemy, alive, combat)' },
    'target.health.max': { type: 'target', description: 'Target maximum health' },
    'target.npcid': { type: 'target', description: 'NPC ID from GUID' },
    'target.bypass_combat': { type: 'target', description: 'NPC bypasses combat checks (from _npcdata.yaml)' },
    'target.should_stun': { type: 'target', description: 'NPC should be stunned (from _npcdata.yaml)' },
    'target.should_slow': { type: 'target', description: 'NPC should be slowed (from _npcdata.yaml)' },
    'target.has_stealable': { type: 'target', description: 'Target has any stealable buff' },
    'target.has_magic_buff': { type: 'target', description: 'Target has any magic buff' },
    'target.has_enrage': { type: 'target', description: 'Target has an enrage effect' },
    'target.quest_mob': { type: 'target', description: 'Target is a quest mob' },
    'target.attackable': { type: 'target', description: 'Target can be attacked' },
    'target.combat': { type: 'target', description: 'Target is in combat (extended check)' },
    'target.targeting_party': { type: 'target', description: 'Target is targeting a party member' },
    'target.classification': { type: 'target', description: 'Target classification (elite, rare, etc.)' },
    'target.threat': { type: 'target', description: 'Threat level on target (0-3, -1 if N/A)' },
    'target.lootable': { type: 'target', description: 'Target is lootable' },
    'target.guid': { type: 'target', description: 'Target has a GUID (for existence checks)' },
    'target.dispelable.SPELL': { type: 'target', description: 'Target has dispellable buff/enrage for SPELL' },
    'target.dispelable.list.SPELL': { type: 'target', description: 'Target dispellable with dispel_list filtering' },
    'target.stunned': { type: 'target', description: 'Target is stunned' },
    'target.rooted': { type: 'target', description: 'Target is rooted' },
    'target.silenced': { type: 'target', description: 'Target is silenced' },
    'target.slowed': { type: 'target', description: 'Target is slowed' },
    'target.interrupt_immune': { type: 'target', description: 'Target is immune to interrupts' },
    'target.stun_immune': { type: 'target', description: 'Target is immune to stuns' },

    // Focus
    'focus.exists': { type: 'unit', description: 'Focus target exists' },
    'focus.alive': { type: 'unit', description: 'Focus is alive' },
    'focus.dead': { type: 'unit', description: 'Focus is dead' },
    'focus.enemy': { type: 'unit', description: 'Focus is an enemy' },
    'focus.friendly': { type: 'unit', description: 'Focus is friendly' },
    'focus.range': { type: 'unit', description: 'Distance to focus' },
    'focus.guid': { type: 'unit', description: 'Focus has a GUID (for existence checks)' },
    'focus.health.max': { type: 'unit', description: 'Focus maximum health' },
    'focus.casting': { type: 'unit', description: 'Focus is casting' },
    'focus.channeling': { type: 'unit', description: 'Focus is channeling' },
    'focus.casting.interruptible': { type: 'unit', description: 'Focus cast can be interrupted' },
    'focus.casting.remains': { type: 'unit', description: 'Focus cast time remaining' },
    'focus.casting.elapsed': { type: 'unit', description: 'Focus cast time elapsed' },
    'focus.casting.important': { type: 'unit', description: 'Focus cast is in _interrupts.yaml' },
    'focus.casting.targeting_me': { type: 'unit', description: 'Focus cast is targeting player' },
    'focus.casting.spell': { type: 'unit', description: 'Focus currently casting spell ID' },
    'focus.casting.SPELL_NAME': { type: 'unit', description: 'Focus is casting specific spell by name', example: 'if=focus.casting.shadow_bolt' },
    'focus.buff.remains(SPELL)': { type: 'unit', description: 'Focus buff remaining duration (function syntax)', example: 'if=focus.buff.remains(renew)>0' },
    'focus.buff.stacks(SPELL)': { type: 'unit', description: 'Focus buff stack count (function syntax)' },
    'focus.debuff.remains(SPELL)': { type: 'unit', description: 'Focus debuff remaining duration (function syntax)' },
    'focus.debuff.stacks(SPELL)': { type: 'unit', description: 'Focus debuff stack count (function syntax)' },
    'focus.buff.up(SPELL)': { type: 'unit', description: 'Focus has buff (function syntax)' },
    'focus.debuff.up(SPELL)': { type: 'unit', description: 'Focus has debuff (function syntax)' },

    // Mouseover
    'mouseover.exists': { type: 'unit', description: 'Mouseover unit exists' },
    'mouseover.alive': { type: 'unit', description: 'Mouseover is alive' },
    'mouseover.dead': { type: 'unit', description: 'Mouseover is dead' },
    'mouseover.enemy': { type: 'unit', description: 'Mouseover is an enemy' },
    'mouseover.friendly': { type: 'unit', description: 'Mouseover is friendly' },
    'mouseover.range': { type: 'unit', description: 'Distance to mouseover' },
    'mouseover.guid': { type: 'unit', description: 'Mouseover has a GUID (for existence checks)' },
    'mouseover.health.max': { type: 'unit', description: 'Mouseover maximum health' },
    'mouseover.lootable': { type: 'unit', description: 'Mouseover is lootable' },
    'mouseover.casting': { type: 'unit', description: 'Mouseover is casting' },
    'mouseover.channeling': { type: 'unit', description: 'Mouseover is channeling' },
    'mouseover.casting.interruptible': { type: 'unit', description: 'Mouseover cast can be interrupted' },
    'mouseover.casting.remains': { type: 'unit', description: 'Mouseover cast time remaining' },
    'mouseover.casting.elapsed': { type: 'unit', description: 'Mouseover cast time elapsed' },
    'mouseover.casting.important': { type: 'unit', description: 'Mouseover cast is in _interrupts.yaml' },
    'mouseover.casting.targeting_me': { type: 'unit', description: 'Mouseover cast is targeting player' },
    'mouseover.casting.spell': { type: 'unit', description: 'Mouseover currently casting spell ID' },
    'mouseover.casting.SPELL_NAME': { type: 'unit', description: 'Mouseover is casting specific spell by name', example: 'if=mouseover.casting.fear' },
    'mouseover.buff.remains(SPELL)': { type: 'unit', description: 'Mouseover buff remaining duration (function syntax)', example: 'if=mouseover.buff.remains(renew)>0' },
    'mouseover.buff.stacks(SPELL)': { type: 'unit', description: 'Mouseover buff stack count (function syntax)' },
    'mouseover.debuff.remains(SPELL)': { type: 'unit', description: 'Mouseover debuff remaining duration (function syntax)', example: 'if=mouseover.debuff.remains(dot)<=0' },
    'mouseover.debuff.stacks(SPELL)': { type: 'unit', description: 'Mouseover debuff stack count (function syntax)' },
    'mouseover.buff.up(SPELL)': { type: 'unit', description: 'Mouseover has buff (function syntax)' },
    'mouseover.debuff.up(SPELL)': { type: 'unit', description: 'Mouseover has debuff (function syntax)' },

    // Pet
    'pet.exists': { type: 'pet', description: 'Pet exists' },
    'pet.alive': { type: 'pet', description: 'Pet is alive' },
    'pet.dead': { type: 'pet', description: 'Pet is dead' },
    'pet.guid': { type: 'pet', description: 'Pet has a GUID (for existence checks)' },
    'pet.health.max': { type: 'pet', description: 'Pet maximum health' },
    'pet.nearby_enemies': { type: 'pet', description: 'Enemies within 8 yards of pet' },
    'pet.nearbyenemies': { type: 'pet', description: 'Alias for pet.nearby_enemies' },

    // Enemy counts
    'active_enemies': { type: 'combat', description: 'Enemies in combat range', example: 'if=active_enemies>=3' },
    'spell_targets': { type: 'combat', description: 'Same as active_enemies' },
    'enemies.8y': { type: 'combat', description: 'Enemies within 8 yards' },
    'enemies.15y': { type: 'combat', description: 'Enemies within 15 yards' },
    'enemies.40y': { type: 'combat', description: 'Enemies within 40 yards' },
    'enemies.combat.8y': { type: 'combat', description: 'Enemies in combat within 8y' },
    'enemies.combat.15y': { type: 'combat', description: 'Enemies in combat within 15y' },
    'enemies.combat.40y': { type: 'combat', description: 'Enemies in combat within 40y' },
    'enemies.inrange(N)': { type: 'combat', description: 'Enemies within N yards (dynamic)', example: 'if=enemies.inrange(12)>=2' },
    'enemies.combat.inrange(N)': { type: 'combat', description: 'Enemies in combat within N yards (dynamic)', example: 'if=enemies.combat.inrange(10)>=3' },
    'combat.enemies': { type: 'combat', description: 'Enemies in combat (deprecated)' },
    'combat.enemies.8y': { type: 'combat', description: 'Enemies in combat within 8y' },
    'combat.enemies.15y': { type: 'combat', description: 'Enemies in combat within 15y' },
    'combat.enemies.40y': { type: 'combat', description: 'Enemies in combat within 40y' },
    'combat.enemies.inrange(N)': { type: 'combat', description: 'Enemies in combat within N yards (deprecated, use enemies.combat.inrange)' },

    // Group/Healing
    'group.count(EXPR)': { type: 'group', description: 'Count of members matching expression (use cycle.* inside)', example: 'if=group.count(cycle.health.pct<35)>=2' },
    'group.lowest.health.pct': { type: 'group', description: 'Lowest member health %', example: 'if=group.lowest.health.pct<50' },
    'group.lowest.range': { type: 'group', description: 'Range to lowest member' },
    'group.tanks.lowest.health.pct': { type: 'group', description: 'Lowest tank health %' },
    'group.healers.lowest.health.pct': { type: 'group', description: 'Lowest healer health %' },
    'group.dps.lowest.health.pct': { type: 'group', description: 'Lowest DPS health %' },
    'group.under_pct_30': { type: 'group', description: 'Members under 30% health' },
    'group.under_pct_50': { type: 'group', description: 'Members under 50% health' },
    'group.under_pct_75': { type: 'group', description: 'Members under 75% health' },
    'group.under_pct_80': { type: 'group', description: 'Members under 80% health' },
    'group.in_range_10': { type: 'group', description: 'Members within 10 yards' },
    'group.in_range_15': { type: 'group', description: 'Members within 15 yards' },
    'group.in_range_30': { type: 'group', description: 'Members within 30 yards' },
    'group.in_range_40': { type: 'group', description: 'Members within 40 yards' },
    'group.under_pct_85': { type: 'group', description: 'Members under 85% health' },
    'group.under_pct_90': { type: 'group', description: 'Members under 90% health' },
    'group.lowest.health.current': { type: 'group', description: 'Lowest member current HP' },
    'group.lowest.health.deficit': { type: 'group', description: 'Lowest member missing HP' },
    'group.lowest.dead': { type: 'group', description: 'Lowest member is dead' },
    'group.lowest.guid': { type: 'group', description: 'Lowest member has a GUID' },
    'group.tanks.lowest.health.current': { type: 'group', description: 'Lowest tank current HP' },
    'group.tanks.lowest.health.deficit': { type: 'group', description: 'Lowest tank missing HP' },
    'group.healers.lowest.health.current': { type: 'group', description: 'Lowest healer current HP' },
    'group.healers.lowest.health.deficit': { type: 'group', description: 'Lowest healer missing HP' },
    'group.dps.lowest.health.current': { type: 'group', description: 'Lowest DPS current HP' },
    'group.dps.lowest.health.deficit': { type: 'group', description: 'Lowest DPS missing HP' },
    'group.buff.SPELL.count': { type: 'group', description: 'Members with buff' },
    'group.buff.SPELL.lowest.health.pct': { type: 'group', description: 'HP % of lowest with buff' },
    'group.buff.SPELL.lowest.health.current': { type: 'group', description: 'HP of lowest with buff' },
    'group.buff.SPELL.lowest.health.deficit': { type: 'group', description: 'Missing HP of lowest with buff' },
    'group.buff.SPELL.lowest.range': { type: 'group', description: 'Range to lowest with buff' },
    'group.missing.SPELL.count': { type: 'group', description: 'Members without buff' },
    'group.missing.SPELL.lowest.health.pct': { type: 'group', description: 'HP % of lowest without buff' },
    'group.missing.SPELL.lowest.health.current': { type: 'group', description: 'HP of lowest without buff' },
    'group.missing.SPELL.lowest.health.deficit': { type: 'group', description: 'Missing HP of lowest without buff' },
    'group.missing.SPELL.lowest.range': { type: 'group', description: 'Range to lowest without buff' },

    // Cycle context expressions (used in cycle= conditions)
    'cycle.health.current': { type: 'cycle', description: 'Current cycle member health value' },
    'cycle.health.max': { type: 'cycle', description: 'Current cycle member max health' },
    'cycle.health.pct': { type: 'cycle', description: 'Current cycle member health %' },
    'cycle.health.deficit': { type: 'cycle', description: 'Current cycle member missing HP' },
    'cycle.range': { type: 'cycle', description: 'Range to current cycle member' },
    'cycle.buff.SPELL.up': { type: 'cycle', description: 'Cycle member has your buff' },
    'cycle.buff.SPELL.up.any': { type: 'cycle', description: 'Cycle member has buff from any source' },
    'cycle.buff.SPELL.down': { type: 'cycle', description: 'Cycle member missing your buff' },
    'cycle.buff.SPELL.down.any': { type: 'cycle', description: 'Cycle member missing buff from all sources' },
    'cycle.buff.SPELL.remains': { type: 'cycle', description: 'Your buff duration on cycle member' },
    'cycle.buff.SPELL.remains.any': { type: 'cycle', description: 'Any buff duration on cycle member' },
    'cycle.buff.SPELL.elapsed': { type: 'cycle', description: 'Time since buff applied on cycle member' },
    'cycle.buff.SPELL.stack': { type: 'cycle', description: 'Your buff stacks on cycle member' },
    'cycle.buff.SPELL.mine': { type: 'cycle', description: 'Cycle member has your buff (player-applied)' },
    'cycle.debuff.SPELL.up': { type: 'cycle', description: 'Cycle member has debuff' },
    'cycle.debuff.SPELL.down': { type: 'cycle', description: 'Cycle member missing debuff' },
    'cycle.debuff.SPELL.remains': { type: 'cycle', description: 'Debuff duration on cycle member' },
    'cycle.debuff.SPELL.elapsed': { type: 'cycle', description: 'Time since debuff applied on cycle member' },
    'cycle.debuff.SPELL.elapsed.any': { type: 'cycle', description: 'Time since debuff applied (any source)' },
    'cycle.debuff.SPELL.stack': { type: 'cycle', description: 'Debuff stacks on cycle member' },
    'cycle.dispelable.SPELL': { type: 'cycle', description: 'Cycle member has dispellable debuff for SPELL' },
    'cycle.dispelable.list.SPELL': { type: 'cycle', description: 'Cycle member dispellable with dispel_list filtering' },

    // Nameplate buff/debuff aggregations
    'nameplates.buff.SPELL.count': { type: 'buff', description: 'Count of nameplates with your buff active (player-applied only). Use .any for any source.' },
    'nameplates.buff.SPELL.lowest': { type: 'buff', description: 'Lowest remaining buff duration on nameplates (player-applied only). Use .any for any source.' },
    'nameplates.buff.SPELL.highest': { type: 'buff', description: 'Highest remaining buff duration on nameplates (player-applied only). Use .any for any source.' },
    'nameplates.buff.SPELL.count.any': { type: 'buff', description: 'Count of nameplates with a buff from any source' },
    'nameplates.buff.SPELL.lowest.any': { type: 'buff', description: 'Lowest remaining buff duration on nameplates from any source' },
    'nameplates.buff.SPELL.highest.any': { type: 'buff', description: 'Highest remaining buff duration on nameplates from any source' },

    'nameplates.debuff.SPELL.count': { type: 'debuff', description: 'Count of nameplates with your debuff active (player-applied only). Use .any for any source.' },
    'nameplates.debuff.SPELL.lowest': { type: 'debuff', description: 'Lowest remaining debuff duration on nameplates (player-applied only). Use .any for any source.' },
    'nameplates.debuff.SPELL.highest': { type: 'debuff', description: 'Highest remaining debuff duration on nameplates (player-applied only). Use .any for any source.' },
    'nameplates.debuff.SPELL.count.any': { type: 'debuff', description: 'Count of nameplates with a debuff from any source' },
    'nameplates.debuff.SPELL.lowest.any': { type: 'debuff', description: 'Lowest remaining debuff duration on nameplates from any source' },
    'nameplates.debuff.SPELL.highest.any': { type: 'debuff', description: 'Highest remaining debuff duration on nameplates from any source' },

    // Totem
    'totem.SPELL.up': { type: 'totem', description: 'Totem is active', example: 'if=totem.fire_elemental.up' },
    'totem.SPELL.remains': { type: 'totem', description: 'Time until totem expires' },

    // Equipment
    'trinket_1.ready': { type: 'equipment', description: 'Trinket 1 is off cooldown' },
    'trinket_1.cd': { type: 'equipment', description: 'Trinket 1 cooldown remaining' },
    'trinket_1.id': { type: 'equipment', description: 'Trinket 1 item ID' },
    'trinket_1.usable': { type: 'equipment', description: 'Trinket 1 is usable' },
    'trinket_1.sync': { type: 'equipment', description: 'Trinket 1 ready + burst check', example: 'if=trinket_1.sync' },
    'trinket_2.ready': { type: 'equipment', description: 'Trinket 2 is off cooldown' },
    'trinket_2.cd': { type: 'equipment', description: 'Trinket 2 cooldown remaining' },
    'trinket_2.id': { type: 'equipment', description: 'Trinket 2 item ID' },
    'trinket_2.usable': { type: 'equipment', description: 'Trinket 2 is usable' },
    'trinket_2.sync': { type: 'equipment', description: 'Trinket 2 ready + burst check' },
    'main_hand.2h': { type: 'equipment', description: '1 if using 2H weapon' },
    'mainhand.enchant.up': { type: 'equipment', description: 'Main hand has temp enchant' },
    'mainhand.enchant.remains': { type: 'equipment', description: 'Main hand enchant time left' },
    'mainhand.enchant.id': { type: 'equipment', description: 'Main hand enchant ID (0 if none)' },
    'offhand.enchant.up': { type: 'equipment', description: 'Off hand has temp enchant' },
    'offhand.enchant.remains': { type: 'equipment', description: 'Off hand enchant time left' },
    'offhand.enchant.id': { type: 'equipment', description: 'Off hand enchant ID (0 if none)' },
    'helm.ready': { type: 'equipment', description: 'Helm on-use is off cooldown' },
    'helm.cd': { type: 'equipment', description: 'Helm on-use cooldown remaining' },
    'helm.id': { type: 'equipment', description: 'Helm item ID' },
    'helm.usable': { type: 'equipment', description: 'Helm on-use is usable' },
    'cloak.ready': { type: 'equipment', description: 'Cloak on-use is off cooldown' },
    'cloak.cd': { type: 'equipment', description: 'Cloak on-use cooldown remaining' },
    'cloak.id': { type: 'equipment', description: 'Cloak item ID' },
    'cloak.usable': { type: 'equipment', description: 'Cloak on-use is usable' },
    'wrist.ready': { type: 'equipment', description: 'Wrist on-use is off cooldown' },
    'wrist.cd': { type: 'equipment', description: 'Wrist on-use cooldown remaining' },
    'wrist.id': { type: 'equipment', description: 'Wrist item ID' },
    'wrist.usable': { type: 'equipment', description: 'Wrist on-use is usable' },
    'belt.ready': { type: 'equipment', description: 'Belt on-use is off cooldown' },
    'belt.cd': { type: 'equipment', description: 'Belt on-use cooldown remaining' },
    'belt.id': { type: 'equipment', description: 'Belt item ID' },
    'belt.usable': { type: 'equipment', description: 'Belt on-use is usable' },
    'weapon.ready': { type: 'equipment', description: 'Weapon on-use is off cooldown' },
    'weapon.cd': { type: 'equipment', description: 'Weapon on-use cooldown remaining' },
    'weapon.id': { type: 'equipment', description: 'Weapon item ID' },
    'weapon.usable': { type: 'equipment', description: 'Weapon on-use is usable' },
    'equipped.ITEM_ID': { type: 'equipment', description: 'Check if item ID is equipped' },
    'set_bonus.TIER_2pc': { type: 'equipment', description: 'Have 2-piece tier bonus' },
    'set_bonus.TIER_4pc': { type: 'equipment', description: 'Have 4-piece tier bonus' },

    // Consumables
    'healthstone.ready': { type: 'consumable', description: 'Healthstone is ready' },
    'healthstone.cd': { type: 'consumable', description: 'Healthstone cooldown' },
    'health_potion.ready': { type: 'consumable', description: 'Health potion is ready' },
    'health_potion.cd': { type: 'consumable', description: 'Health potion cooldown' },
    'mana_potion.ready': { type: 'consumable', description: 'Mana potion is ready' },
    'mana_potion.cd': { type: 'consumable', description: 'Mana potion cooldown' },
    'combat_potion.ready': { type: 'consumable', description: 'Combat potion is ready' },
    'combat_potion.cd': { type: 'consumable', description: 'Combat potion cooldown' },
    'rune.ready': { type: 'consumable', description: 'Augment rune is ready' },
    'rune.cd': { type: 'consumable', description: 'Augment rune cooldown' },

    // Interrupts (from _interrupts.yaml)
    'interrupts.target.ready': { type: 'interrupt', description: 'Target casting interruptible spell' },
    'interrupts.target.stun.ready': { type: 'interrupt', description: 'Target casting stun-able spell' },
    'interrupts.focus.ready': { type: 'interrupt', description: 'Focus casting interruptible spell' },
    'interrupts.focus.stun.ready': { type: 'interrupt', description: 'Focus casting stun-able spell' },
    'interrupts.mouseover.ready': { type: 'interrupt', description: 'Mouseover casting interruptible spell' },
    'interrupts.mouseover.stun.ready': { type: 'interrupt', description: 'Mouseover casting stun-able spell' },
    'interrupts.8y.ready': { type: 'interrupt', description: 'Any enemy in 8y casting interruptible' },
    'interrupts.8y.stun.ready': { type: 'interrupt', description: 'Any enemy in 8y casting stun-able' },
    'interrupts.8y.count': { type: 'interrupt', description: 'Count of enemies in 8y casting interruptible' },
    'interrupts.8y.stun.count': { type: 'interrupt', description: 'Count of enemies in 8y casting stun-able' },
    'interrupts.10y.ready': { type: 'interrupt', description: 'Any enemy in 10y casting interruptible' },
    'interrupts.10y.stun.ready': { type: 'interrupt', description: 'Any enemy in 10y casting stun-able' },
    'interrupts.10y.count': { type: 'interrupt', description: 'Count of enemies in 10y casting interruptible' },
    'interrupts.10y.stun.count': { type: 'interrupt', description: 'Count of enemies in 10y casting stun-able' },
    'interrupts.15y.ready': { type: 'interrupt', description: 'Any enemy in 15y casting interruptible' },
    'interrupts.15y.stun.ready': { type: 'interrupt', description: 'Any enemy in 15y casting stun-able' },
    'interrupts.15y.count': { type: 'interrupt', description: 'Count of enemies in 15y casting interruptible' },
    'interrupts.15y.stun.count': { type: 'interrupt', description: 'Count of enemies in 15y casting stun-able' },
    'interrupts.40y.ready': { type: 'interrupt', description: 'Any enemy in 40y casting interruptible' },
    'interrupts.40y.stun.ready': { type: 'interrupt', description: 'Any enemy in 40y casting stun-able' },
    'interrupts.40y.count': { type: 'interrupt', description: 'Count of enemies in 40y casting interruptible' },
    'interrupts.40y.stun.count': { type: 'interrupt', description: 'Count of enemies in 40y casting stun-able' },

    // Defensives (from _defensives.yaml)
    'defensives.ready': { type: 'defensive', description: 'Enemy casting dangerous spell' },
    'defensives.ready.aoe': { type: 'defensive', description: 'Enemy casting AoE spell' },

    // Reflectable (from _reflectable.yaml)
    'reflectable.ready': { type: 'reflect', description: 'Enemy casting reflectable spell' },

    // System state
    'state.rotation': { type: 'state', description: 'Rotation enabled/disabled' },
    'state.cds': { type: 'state', description: 'Cooldowns enabled/disabled', example: 'if=state.cds' },
    'state.aoe': { type: 'state', description: 'AOE mode enabled/disabled' },
    'state.blocked_inputs': { type: 'state', description: 'Input blocking enabled' },

    // Variables and config
    'var.VARNAME': { type: 'variable', description: 'User-defined variable value', example: 'if=var.pooling' },
    'config.SETTING': { type: 'config', description: 'User config setting value', example: 'if=config.use_aoe' },
    'settings.SETTING': { type: 'config', description: 'Alias for config.SETTING' },

    // One Button Assistant
    'one_button_assistant.SPELL': { type: 'assistant', description: '1 if spell is currently shown by one-button assistant', example: 'if=one_button_assistant.arcane_shot' },
    'one_button_assistant.SPELL.elapsed': { type: 'assistant', description: 'Seconds since spell was last shown (999 if never)', example: 'if=one_button_assistant.kill_command.elapsed<5' },

    // Aura point values
    'player.buff.SPELL.points.1': { type: 'buff', description: 'Buff effect point 1 value' },
    'player.buff.SPELL.points.2': { type: 'buff', description: 'Buff effect point 2 value' },
    'player.buff.SPELL.points.3': { type: 'buff', description: 'Buff effect point 3 value' },
    'player.buff.SPELL.points.4': { type: 'buff', description: 'Buff effect point 4 value' },
    'target.debuff.SPELL.points.1': { type: 'debuff', description: 'Target debuff effect point 1 value' },
    'target.debuff.SPELL.points.2': { type: 'debuff', description: 'Target debuff effect point 2 value' },
    'player.debuff.SPELL.points.1': { type: 'debuff', description: 'Player debuff effect point 1 value' },
    'player.debuff.SPELL.points.2': { type: 'debuff', description: 'Player debuff effect point 2 value' },
    'target.buff.SPELL.points.1': { type: 'buff', description: 'Target buff effect point 1 value' },
    'target.buff.SPELL.points.2': { type: 'buff', description: 'Target buff effect point 2 value' },

    // Literals
    'true': { type: 'literal', description: 'Always true (1)' },
    'false': { type: 'literal', description: 'Always false (0)' },
};

// Step options for action lines
export const STEP_OPTIONS: Record<string, StepOptionInfo> = {
    'range_check': {
        description: 'Control range validation for this action',
        values: ['target', 'mouseover', 'focus', 'mob_count_8y', 'mob_count_40y', 'none'],
        snippet: 'range_check=${1|target,mouseover,focus,mob_count_8y,none|}'
    },
    'rangecheck': {
        description: 'SimC compatibility alias for range_check',
        values: ['target', 'mouseover', 'focus', 'mob_count_8y', 'mob_count_40y', 'none'],
        snippet: 'rangecheck=${1|target,mouseover,focus,mob_count_8y,none|}'
    },
    'casting_check': {
        description: 'Only cast while player is casting specific spell',
        values: ['none', 'any', 'SPELL_ID', 'spell_name'],
        snippet: 'casting_check=${1:any}'
    },
    'cast_remains': {
        description: 'Only during last X seconds of current cast',
        snippet: 'cast_remains=${1:0.5}'
    },
    'channel_remains': {
        description: 'Only during last X seconds of current channel',
        snippet: 'channel_remains=${1:1.0}'
    },
    'interrupt': {
        description: 'Allow this action to interrupt current cast',
        values: ['true', 'false'],
        snippet: 'interrupt=true'
    },
    'ignore_cooldown': {
        description: 'Skip cooldown check for this spell',
        values: ['true', 'false'],
        snippet: 'ignore_cooldown=true'
    },
    'ignore_usable': {
        description: 'Skip usability check for this spell',
        values: ['true', 'false'],
        snippet: 'ignore_usable=true'
    },
    'ignore_movement': {
        description: 'Allow casting while moving (for spells like Scorch)',
        values: ['true', 'false'],
        snippet: 'ignore_movement=true'
    },
    'hotkey': {
        description: 'Override the virtual key code for this action',
        snippet: 'hotkey=${1:49}'
    },
    'modifier': {
        description: 'Modifier key (16=Shift, 17=Ctrl, 18=Alt)',
        values: ['16', '17', '18'],
        snippet: 'modifier=${1|16,17,18|}'
    },
    'override': {
        description: 'Use another spell\'s keybind',
        snippet: 'override=${1:spell_name}'
    },
    'delay': {
        description: 'Minimum ms between presses for this spell',
        snippet: 'delay=${1:100}'
    },
    'global_delay': {
        description: 'Set global delay until channel is true',
        snippet: 'global_delay=${1:100}'
    },
    'target': {
        description: 'Direct targeting (lowest, tanks.lowest, etc)',
        values: ['lowest', 'tanks.lowest', 'healers.lowest', 'dps.lowest'],
        snippet: 'target=${1|lowest,tanks.lowest,healers.lowest,dps.lowest|}'
    },
    'cycle': {
        description: 'Cycle through group members',
        values: ['members', 'tanks', 'healers', 'dps'],
        snippet: 'cycle=${1|members,tanks,healers,dps|}'
    },
    'name': {
        description: 'Override step display name (for debug/lookup)',
        snippet: 'name=${1:step_name}'
    },
    'call': {
        description: 'Alias for call_action_list (name required)',
        snippet: 'call=${1:list_name}'
    }
};

// Special actions (not spells)
export const SPECIAL_ACTIONS: Record<string, string> = {
    'trinket_1': 'Use trinket in slot 1',
    'trinket_2': 'Use trinket in slot 2',
    'weapon_onuse': 'Use weapon on-use effect',
    'wrist_onuse': 'Use wrist on-use effect',
    'helm_onuse': 'Use helm on-use effect',
    'cloak_onuse': 'Use cloak on-use effect',
    'belt_onuse': 'Use belt on-use effect',
    'healthstone': 'Use healthstone',
    'health_potion': 'Use health potion',
    'mana_potion': 'Use mana potion',
    'combat_potion': 'Use combat/DPS potion',
    'augment_rune': 'Use augment rune',
    'target_enemy': 'Target nearest attackable enemy',
    'target_mouseover': 'Target current mouseover unit',
    'target_focus': 'Target focus unit',
    'attack_target': 'Start auto-attacking target',
    'interact_target': 'Interact with target (loot, talk)',
    'interact_mouseover': 'Interact with mouseover unit',
    'loot_a_rang': 'Use Loot-A-Rang',
    'return': 'Stop rotation evaluation',
    'stop_casting': 'Cancel current cast',
    'queue_spell': 'Cast spell from Lua addon queue',
    'call_action_list': 'Call another action list',
    'run_action_list': 'Run another action list and restart rotation',
    'focus_target': 'Set focus to current target',
    'focus_mouseover': 'Set focus to current mouseover',
    'focus_party1': 'Set focus to party member 1',
    'focus_party2': 'Set focus to party member 2',
    'focus_party3': 'Set focus to party member 3',
    'focus_party4': 'Set focus to party member 4',
    // Focus raid members 1-40
    'focus_raid1': 'Set focus to raid member 1',
    'focus_raid2': 'Set focus to raid member 2',
    'focus_raid3': 'Set focus to raid member 3',
    'focus_raid4': 'Set focus to raid member 4',
    'focus_raid5': 'Set focus to raid member 5',
    'focus_raid6': 'Set focus to raid member 6',
    'focus_raid7': 'Set focus to raid member 7',
    'focus_raid8': 'Set focus to raid member 8',
    'focus_raid9': 'Set focus to raid member 9',
    'focus_raid10': 'Set focus to raid member 10',
    'focus_raid11': 'Set focus to raid member 11',
    'focus_raid12': 'Set focus to raid member 12',
    'focus_raid13': 'Set focus to raid member 13',
    'focus_raid14': 'Set focus to raid member 14',
    'focus_raid15': 'Set focus to raid member 15',
    'focus_raid16': 'Set focus to raid member 16',
    'focus_raid17': 'Set focus to raid member 17',
    'focus_raid18': 'Set focus to raid member 18',
    'focus_raid19': 'Set focus to raid member 19',
    'focus_raid20': 'Set focus to raid member 20',
    'focus_raid21': 'Set focus to raid member 21',
    'focus_raid22': 'Set focus to raid member 22',
    'focus_raid23': 'Set focus to raid member 23',
    'focus_raid24': 'Set focus to raid member 24',
    'focus_raid25': 'Set focus to raid member 25',
    'focus_raid26': 'Set focus to raid member 26',
    'focus_raid27': 'Set focus to raid member 27',
    'focus_raid28': 'Set focus to raid member 28',
    'focus_raid29': 'Set focus to raid member 29',
    'focus_raid30': 'Set focus to raid member 30',
    'focus_raid31': 'Set focus to raid member 31',
    'focus_raid32': 'Set focus to raid member 32',
    'focus_raid33': 'Set focus to raid member 33',
    'focus_raid34': 'Set focus to raid member 34',
    'focus_raid35': 'Set focus to raid member 35',
    'focus_raid36': 'Set focus to raid member 36',
    'focus_raid37': 'Set focus to raid member 37',
    'focus_raid38': 'Set focus to raid member 38',
    'focus_raid39': 'Set focus to raid member 39',
    'focus_raid40': 'Set focus to raid member 40',
};
